---
- name: Create image for Openstack
  hosts: localhost
  vars:
    auth_url: "192.168.1.26"
    image_url: "http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img"
    image_ref: "cirros-0.3.4-x86_64-disk.img"
    project_name: "admin"
    os_user_domain_name: "Default"
    os_project_domain_name: "Default"
    image_name: "cirros2"
    container_format: "bare"
    disk_format: "qcow2"
  tasks:
    
    - name: Install Python requests module
      pip:
        name: openstacksdk
        state: latest
        
        
    - name: Download cirros image
      get_url:
        url: "{{ image_url }}"
        dest: "/tmp/{{ image_ref }}"

    - name: Upload cirros image to openstack
      os_image:
        state: present
        auth:
          auth_url: "http://{{ auth_url }}:5000/v3"
          project_name: "{{ project_name }}"
          os_user_domain_name: "{{ os_user_domain_name }}"
          os_project_domain_name: "{{ os_project_domain_name }}"
        name: "{{ image_name }}"
        container_format: "{{ container_format }}"
        disk_format: "{{ disk_format }}"
        state: present
        filename: "/tmp/{{ image_ref }}"
