---
- hosts: localhost
  gather_facts: yes
  vars:
    vcenter_server: "vcenter.example.com"
    template_name: "mytemplate"
    datacenter_name: "DC01"
    vm_name: "toto"
  tasks:

    - name: Create Virtual Machines
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        validate_certs: False
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        datacenter: "{{ datacenter_name }}"
        state: poweredon
        folder: /DC01/vm
        networks:
          - name: VM Network
            type: static
            ip: 192.168.1.38
            netmask: 255.255.0.0
            gateway: 192.168.0.2
        customization:
          dns_servers: 192.168.0.1
          hostname: "{{ vm_name }}"
          domain: "example.com"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: webserver

    - debug:
        msg: "{{ webserver }}"

