---
- name: Install Package
  hosts: localhost
  vars:
    package_name: httpd
  tasks:    
    - name: "Install {{ package_name }}  package from variable"
      yum: 
        name: "{{ package_name }}" 
        state: present
      register: package
      
    - debug: 
        msg: "{{ package }}"
        

  
