---
- name: Install Package
  hosts: localhost
  vars: 
    package: from_playbook


  tasks:
    - name: list ip addresse 
      command: ip ad 
      register: ip
 
    - name: Install package nano
      yum: 
        name: nano 
        state: present
      
      
    - name: Install package from variable
      yum: 
        name: "{{ package }}" 
        state: present
        
        
        

  
