---
- name: Install Package
  hosts: localhost
  tasks:
    - name: list ip addresse 
      command: ip ad 
      register: ip
 
    - debug:
        msg: "{{ package }}"
      
    - name: "Install {{ package }}  package from variable"
      yum: 
        name: "{{ package }}" 
        state: present
      register: toto
      
    - debug: 
        msg: "{{ toto }}"
        

  
