---
- name: Install requirement
  hosts: localhost
  remote_user: awx
  gather_facts: no
  become: true

  tasks:
 
    - name: Install Python pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /home

    - name: execute Python pip
      command: "python /home/get-pip.py"

    - name: Install Python requests module
      pip:
        name: openstacksdk
        state: latest
