---
- name: test 123
  hosts: localhost
  connection: ssh
  verbose: "4"
  tasks:
    - name: test1
      command: ip ad 
      register: ip
      
    - debug: 
        msg: "{{ ip }}"
        
    - name: test2
      shell:
        cmd: sudo ls /root 
      register: ls
      
    - debug: 
        msg: "{{ ls }}"
        
    - name: test3
      command: hostname
      register: host
      become: true
      
    - debug: 
        msg: "{{ host }}"
        
    - name: test21
      command: ls /root/ansible 
      register: ls
      become: true
      
    - debug: 
        msg: "{{ ls }}"
        
