---
- name: test 123
  hosts: localhost
  remote_user: root
  tasks:
    - name: test1
      command: ip ad 
      register: ip
      
    - debug: 
        msg: "{{ ip }}"
  
    - name: test2
      shell:
        cmd: cat /tmp/index.html 
      register: cat
      
    - debug: 
        msg: "{{ cat }}"
          
       
    - name: test4
      command: hostname
      register: host
      
    - debug: 
        msg: "{{ host }}"
        
    - name: test21
      command: ls /root/ansible 
      register: ls
      
    - debug: 
        msg: "{{ ls }}"
        
