---
- name: test 123
  hosts: localhost
  remote_user: root
  tasks:
    - name: test1
      command: ip ad 
      register: ip
  
    - name: test2
      shell:
        cmd: sudo cat /tmp/index.html 
      register: cat
      
    - debug: 
        msg: "{{ cat }}"
      
    - debug: 
        msg: "{{ ip }}"
        
    - name: test3
      shell:
        cmd: sudo ls /root 
      register: ls
      
    - debug: 
        msg: "{{ ls }}"
        
    - name: test4
      command: hostname
      register: host
      become: true
      
    - debug: 
        msg: "{{ host }}"
        
    - name: test21
      command: ls /root/ansible 
      register: ls
      become: true
      
    - debug: 
        msg: "{{ ls }}"
        
