---
- name: test 123
  hosts: all
  tasks:
    - name: test1
      command: ip ad 
      register: ip
      
    - debug: 
        msg: "{{ ip }}"
          
       
    - name: test4
      command: hostname
      register: host
      
    - debug: 
        msg: "{{ host }}"

    - name: test5
      shell:
        cmd: pwd
      register: pwd
      
    - debug: 
        msg: "{{ pwd }}"
        
    - name: Display all Environment Variables
      debug:
        var: environment
        
    - name: Display all group names
      debug:
        var: group_names
        
    - name: Display all groups
      debug:
        var: groups
        
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]   
        
    - name: test2
      shell:
        cmd: cat index.html
      register: cat
      
    - debug: 
        msg: "{{ cat }}"
        
    - name: test6
      shell:
        cmd: ansible --version
      register: cat1
      
    - debug: 
        msg: "{{ cat1 }}"
        
