---
- name: test 123
  hosts: localhost
  remote_user: root
  tasks:
    - name: test1
      command: ip ad 
      register: ip
      
    - debug: 
        msg: "{{ ip }}"
          
       
    - name: test4
      command: hostname
      register: host
      
    - debug: 
        msg: "{{ host }}"
        
    - name: test2
      shell:
        cmd: ls 
      register: ls
      
    - debug: 
        msg: "{{ ls }}"
        
