---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "vcenter.example.com"
    template_name: "mytemplate"
    datacenter_name: "DC01"
    vm_name: "changeme"
  tasks:
    - name: Create Virtual Machines
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        validate_certs: False
        name: "{{ vm_name }}-{{ 10000 | random }}"
        template: "{{ template_name }}"
        datacenter: "{{ datacenter_name }}"
        state: poweredon
        folder: /DC01/vm
        wait_for_ip_address: yes
      delegate_to: localhost
      register: server

    - debug:
        msg: "{{ server }}"

